name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
